name: new-client-rust

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-clippy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: new-client-rust

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            new-client-rust/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('new-client-rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format
        run: cargo fmt --check

      - name: Test (default features)
        run: cargo test

      - name: Clippy (default features)
        run: cargo clippy --all-targets

      - name: Test (--no-default-features)
        run: cargo test --no-default-features

      - name: Clippy (--no-default-features)
        run: cargo clippy --all-targets --no-default-features

      - name: Compile Integration Tests
        run: cargo test --features integration-tests --no-run

      - name: Compile (test-util plan bench)
        run: cargo check --features test-util --bench plan

      - name: Compile (tracing feature)
        run: cargo test --features tracing --no-run

      - name: Doc (no-deps)
        run: RUSTDOCFLAGS="-Dwarnings" cargo doc --workspace --exclude tikv-client-proto-build --no-deps
